#在配置文件中注明自己的服务注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769

spring:
  application:
    name: module-zuul

# 以/api-a/ 开头的请求都转发给module-ribbon服务；以/api-b/开头的请求都转发给module-feign服务；
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: module-ribbon
    api-b:
      path: /api-b/**
      serviceId: module-feign
